/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorautomotriz;

/**
 *
 * @author Valeria
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColaKevin3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColaKevin1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ColaKevin2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ColaRefuerzo = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ColaDiego1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        ColaDiego2 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        ColaDiego3 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        Ganador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        ColaRefDiego = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        textoAI = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textoAI2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        Estudio1Pelea = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Estudio2Pelea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        ColaKevin3.setEditable(false);
        ColaKevin3.setColumns(20);
        ColaKevin3.setRows(5);
        jScrollPane1.setViewportView(ColaKevin3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 120));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setText("COLA PRIORIDAD 2 ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 200, -1, -1));

        ColaKevin1.setEditable(false);
        ColaKevin1.setColumns(20);
        ColaKevin1.setRows(5);
        jScrollPane3.setViewportView(ColaKevin1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, 230, 120));

        ColaKevin2.setEditable(false);
        ColaKevin2.setColumns(20);
        ColaKevin2.setRows(5);
        jScrollPane4.setViewportView(ColaKevin2);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 230, 120));

        ColaRefuerzo.setEditable(false);
        ColaRefuerzo.setColumns(20);
        ColaRefuerzo.setRows(5);
        jScrollPane5.setViewportView(ColaRefuerzo);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 230, 120));

        ColaDiego1.setEditable(false);
        ColaDiego1.setColumns(20);
        ColaDiego1.setRows(5);
        jScrollPane6.setViewportView(ColaDiego1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 240, 120));

        ColaDiego2.setEditable(false);
        ColaDiego2.setColumns(20);
        ColaDiego2.setRows(5);
        jScrollPane7.setViewportView(ColaDiego2);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 230, 220, 120));

        ColaDiego3.setEditable(false);
        ColaDiego3.setColumns(20);
        ColaDiego3.setRows(5);
        jScrollPane8.setViewportView(ColaDiego3);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 240, 120));

        jLabel13.setText("Cambiar Velocidad");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, 20));

        Ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GanadorActionPerformed(evt);
            }
        });
        jPanel1.add(Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 760, 210, -1));

        jButton1.setText("DISMINUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        ColaRefDiego.setEditable(false);
        ColaRefDiego.setColumns(20);
        ColaRefDiego.setRows(5);
        jScrollPane9.setViewportView(ColaRefDiego);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 410, 230, 120));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("AI revisando ID: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        textoAI.setEditable(false);
        textoAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAIActionPerformed(evt);
            }
        });
        jPanel1.add(textoAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 60, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Buggatti");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        textoAI2.setEditable(false);
        textoAI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoAI2ActionPerformed(evt);
            }
        });
        jPanel1.add(textoAI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 60, 40));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Ganador:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("AI revisando ID: ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Lamborghini");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, -1, -1));

        Estudio1Pelea.setColumns(20);
        Estudio1Pelea.setRows(5);
        jScrollPane10.setViewportView(Estudio1Pelea);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 280, 160));

        Estudio2Pelea.setColumns(20);
        Estudio2Pelea.setRows(5);
        jScrollPane11.setViewportView(Estudio2Pelea);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, 270, 150));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("COLA DE REFUERZO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setText("COLA PRIORIDAD 2 ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel11.setText("COLA PRIORIDAD 1 ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel17.setText("COLA PRIORIDAD 3 ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel22.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel22.setText("COLA PRIORIDAD 3 ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel14.setText("COLA DE REFUERZO");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jButton2.setText("AUMENTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\valer\\Downloads\\logo copa piston.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 290, 270));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setText("COLA PRIORIDAD 1 ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\valer\\Downloads\\Lambo logo.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 130, 150));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\valer\\Downloads\\NicePng_bugatti-logo-png_620314.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("                                                    COPA PISTON ");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GanadorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String answer = CambiarTiempo1.getText();
            int option = Integer.parseInt(answer);
            Proyecto2Operativos.tiempo = option;

        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"No es una opcion valida");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textoAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAIActionPerformed

    private void textoAI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoAI2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoAI2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ColaDiego1;
    private javax.swing.JTextArea ColaDiego2;
    private javax.swing.JTextArea ColaDiego3;
    private javax.swing.JTextArea ColaKevin1;
    private javax.swing.JTextArea ColaKevin2;
    private javax.swing.JTextArea ColaKevin3;
    private javax.swing.JTextArea ColaRefDiego;
    private javax.swing.JTextArea ColaRefuerzo;
    private javax.swing.JTextArea Estudio1Pelea;
    private javax.swing.JTextArea Estudio2Pelea;
    private javax.swing.JTextField Ganador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField textoAI;
    private javax.swing.JTextField textoAI2;
    // End of variables declaration//GEN-END:variables
}
